In [81]:
import numpy as np

import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])

import pandas as pd

from scipy.optimize import  curve_fit
from sklearn.metrics import r2_score

In [82]:
n = np.array([1,2,3,4,5,6,7])
f_n = np.array((0.023, 0.043, 0.065, 0.086, 0.106, 0.126, 0.148)) *1e3
f_err = 0.001*1e3

m = 199.07 *1e-3
m_err = 0.01 *1e-3

g = 9.79

L = 2.297
L_err = 0.001

In [83]:
lambda_n = 2*L/n
print("lambda_n")
lambda_n

lambda_n


array([4.594     , 2.297     , 1.53133333, 1.1485    , 0.9188    ,
       0.76566667, 0.65628571])

In [84]:
lambda_n_err = 2*L_err/n
print("lambda_n_err")
lambda_n_err

lambda_n_err


array([0.002     , 0.001     , 0.00066667, 0.0005    , 0.0004    ,
       0.00033333, 0.00028571])

In [85]:
v = lambda_n * f_n
print("v")
v

v


array([105.662     ,  98.771     ,  99.53666667,  98.771     ,
        97.3928    ,  96.474     ,  97.13028571])

In [86]:
v_err = 2/n * (f_n*L_err + L*f_err)
print("v_err")
v_err

v_err


array([4.64      , 2.34      , 1.57466667, 1.1915    , 0.9612    ,
       0.80766667, 0.69857143])

In [87]:
print("O valor de v é v = {} +- {}".format(v.mean(), v.std(ddof=1)) )

O valor de v é v = 99.10539319727891 +- 3.0864484006455957


In [88]:
mu = m*g/(v.mean()**2)
mu_err = g*m_err/(v.mean()**2) + 2*m*g/(v.mean()**3) *v.std(ddof=1)

print("mu = {} +- {}".format(mu, mu_err))

mu = 0.0001984238767124645 +- 1.2369033728339506e-05
